### ISSUE TITLE
Active status of queue on /enqueue route

### ISSUE THREAD

**Issue by pfateev** [pfateev/qdub#34]
Currently when a student tries to log in, the front end has no way of knowing the status of the course because we don't start making get requests until we've successfully entered the course.

A boolean in the response (from /enqueue request) that represents the active state of the queue would help the frontend identify whether or not the student is ready to be queued up.

**Comment by triv14** [comment]
Issue is resolved by commit 2449f40c8f470686e34b0f87b71756f5fcadb396.
