### ISSUE TITLE
npm error socket timeout

### ISSUE THREAD

**Issue by Soreloser2** [pfateev/qdub#40]
Hi, I was attempting to test the code for the peer review process this week. Unfortunately I ran into a problem running the `docker-compose up --build` command, specifically in the `npm install` phase. Here is the error I get (after 27 seconds of running):

```
#0 27.89 npm ERR! code ERR_SOCKET_TIMEOUT
#0 27.89 npm ERR! network Socket timeout
#0 27.89 npm ERR! network This is a problem related to network connectivity.
#0 27.89 npm ERR! network In most cases you are behind a proxy or have bad network settings.
#0 27.89 npm ERR! network
#0 27.89 npm ERR! network If you are behind a proxy, please make sure that the
#0 27.89 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
#0 27.89
#0 27.89 npm ERR! A complete log of this run can be found in:
#0 27.89 npm ERR!     /root/.npm/_logs/2023-02-27T02_10_24_153Z-debug-0.log
------
failed to solve: executor failed running [/bin/sh -c npm install]: exit code: 1
```
I am executing the code from a Windows 11 machine, but from what I understand this is being run from a Docker container instance, so I'm not sure that matters. I have default installs of Docker, WSL, and npm (although again I think the npm install shouldn't matter). I have a stable wired internet connection with no configured proxy in my windows install, so I don't think it is an issue with my own connections, but instead may have to do with the containerized connection?

I'm not sure where to find that run log as it is not found in my own file system, and Docker shows no containers, images, or volumes present. I am fairly fresh to Docker though, so it's possible I missed it.

I would love some help so I can continue reviewing the project!

**Comment by pfateev** [comment]
Thanks @Soreloser2. 
Did you start the Docker desktop application before running those commands?
Can you try `docker-compose up -d --build`? We forgot to add `-d` flag that to the docs.
If it still doesn't work, can you make sure to run `docker-compose down`
Then `docker system prune`
Then try it again?

Let me know if that still doesn't work.

**Comment by pfateev** [comment]
@Soreloser2 [Here is an article to try](https://stackoverflow.com/questions/67657599/npm-err-code-err-socket-timeout-on-creating-new-project-using-ng-new-appname).
The problem is that no one on the team can recreate the issue you're having, so it's hard to tell what to do next...
Is it possible that the port Docker is trying to use is already in use on your end?

**Comment by Soreloser2** [comment]
Hi @pfateev, thanks for your response. I tried all of those options, and one of those eventually did work. I'm not sure which one it was unfortunately. Due to the error I would suspect it was me having an npm proxy in my config, even though my npm install is fairly new and unmodified from the default.
