### ISSUE TITLE
All students share the same studentView regardless of their position

### ISSUE THREAD

**Issue by pfateev** [pfateev/qdub#46]
<img width="1423" alt="IMG_7454" src="https://user-images.githubusercontent.com/123142067/221761248-ec237306-cf87-4794-9ad5-4978d1c4797a.png">
In the picture you see that 2 different netId's are used, but the students start receiving the same information from the backend.
What's curious about this, is this is the studentView which means they shouldn't even see the studentName because that's strictly for TA's.

Here is the backend view:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/123142067/221763384-479e414c-54e4-477b-84c1-3e19d2b0d04d.png">
The TA status is correctly set, but for some reason the same exact response is being generated
![image](https://user-images.githubusercontent.com/123142067/221764068-96e9b520-6ed9-4e83-b749-8b5a7e8d86ba.png)
Part of the problem is probably that we're sending the same size but without position to every student. But we're never even reaching that case as of right now where it says "IN THE ELSE"

**Comment by jaredtran2001** [comment]
Issue was that isTA was a string and not a boolean and when grabbing position of the student we must grab their respective positions and not just the number of people in queue.
