### ISSUE TITLE
StepOut not working correctly

### ISSUE THREAD

**Issue by pfateev** [pfateev/qdub#53]
If student steps out, with one student ahead of them being helped and then the TA hits "finish", the "stepped out" student will be helped even though the person right behind them is supposed to go.

**Comment by triv14** [comment]
Fix bug in commit #[6aba69796909ce87fde5864df2776b7af05419e4](https://github.com/pfateev/qdub/commit/6aba69796909ce87fde5864df2776b7af05419e4)
