### ISSUE TITLE
Input validation on student course selection

### ISSUE THREAD

**Issue by pfateev** [pfateev/qdub#69]
![image](https://user-images.githubusercontent.com/123142067/223275977-7ecfba38-e55f-40b2-bce1-43f4e2ac0c6f.png)
When you don't input your question, all of the input fields change to red which is a little visually confusing.

Maybe only signal with the red for the specific missing input?
Also adding a little message could be nice?
Here is an example and a [link to the docs:](https://chakra-ui.com/docs/components/form-control)
![image](https://user-images.githubusercontent.com/123142067/223276628-64bb88a8-db6f-44b7-be74-b49aaf6f41ec.png)

**Comment by what-it-izz** [comment]
looking

**Comment by what-it-izz** [comment]
fixed - for student view

**Comment by what-it-izz** [comment]
see https://github.com/pfateev/qdub/pull/74#issue-1612727926
