### ISSUE TITLE
Input validation on TA course selection

### ISSUE THREAD

**Issue by pfateev** [pfateev/qdub#72]
![image](https://user-images.githubusercontent.com/123142067/223318087-99065618-3c35-426a-916c-43fc9a63fdfe.png)
If a TA doesn't choose a course, I think it would be nice to give them a message like "You must select a course" or whatever. 

The other issue is that if you try to activate without a course selected and then go to the "notify" tab, everything there will be outlined in red too:
![image](https://user-images.githubusercontent.com/123142067/223318245-c701a091-c464-48d3-a4ba-c6fbbb0feb71.png)
This is not a huge deal, but probably shouldn't be happening.

**Comment by what-it-izz** [comment]
fixed see https://github.com/pfateev/qdub/pull/74#issue-1612727926
